### ISSUE TITLE
Rename "2-point-data" in model annotations

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/pseudoace#33]
Names starting with non-alphabetic characters cause issues with datalog queries.

We should re-name any class/attribute names in the annotated ACeDB models accordingly.

`2-point-data` is the only one I'm aware of.

**Comment by tuli** [comment]
Renaming as two-point-data is fine, genetically more accurate in fact.

**Comment by Paul-Davis** [comment]
So is this something that needs to be done in the annotated models file or both?

**Comment by mgrbyte** [comment]
At least in the annotated models; would not need the special syntax (^) if applied to the ACeDB model first.

**Comment by mgrbyte** [comment]
@Paul-Davis @tuli Is this something that could go into WS255?

**Comment by tuli** [comment]
I believe so. @Paul-Davis would you like me to write a proposal to models?

**Comment by Paul-Davis** [comment]
@tuli is 2-point-data used in acedb tools/displays where this change would break the functionality?

;)

**Comment by tuli** [comment]
Do you mean like the genetic map? 

What do you mean custom? Isn't everything in acedb custom made?

**Comment by Paul-Davis** [comment]
@tuli yes things like genetic map.

**Comment by Paul-Davis** [comment]
I don't believe this is resolved??!

**Comment by mgrbyte** [comment]
@Paul-Davis Seems to have been [done](https://github.com/WormBase/pseudoace/blame/master/models/models.wrm.annot) in the annotated models?

**Comment by Paul-Davis** [comment]
does it?

**Comment by Paul-Davis** [comment]
2-point-data model hasn't been touched since before you collapsed the WSXYZ model files down into a single file for tracking differences (version control vs versions of the file).

**Comment by mgrbyte** [comment]
Looks like it was actually previously done (as far back as WS249) https://github.com/WormBase/pseudoace/blame/master/models/models.wrm.annot#L897

**Comment by Paul-Davis** [comment]
I'll close it again then as it was a non-issues ;)
