### ISSUE TITLE
Fix report comparison issues

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/pseudoace#35]
- Ensure the reference data dumped in the pipline is uniform with repsect to its encoding of ids/object-names
- Check that the various object-ids in the datomic db side are uniformly serialized to the same string form

**Comment by mgrbyte** [comment]
@gw3 Are there any classes which use temporary ids which are _never_ the same across releases?

**Comment by gw3** [comment]
The Protein IDs are not guaranteed to remain constant between releases.
The Transcript IDs with Method=Coding_transcript are not guaranteed to
remain constant.

There is however a majority of instances in these two objects that will
retain a consistent ID.
Gary

On 19/04/16 17:21, Matt Russell wrote:

@gw3 https://github.com/gw3 Are there any classes which use temporary ids
which are _never_ the same across releases?

**Comment by mgrbyte** [comment]
Closing. 

After 08210be13833f14aa4cbb42f58050922bdbbd711, when the missing vs added counts in the report differ and both are non-zero, we write two files such that we easily run `diff` over the ids between what was in the reference data vs the database.
