### ISSUE TITLE
reg2bins is private but being used by datomic-to-catalyst

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/pseudoace#42]
We should be looking into making the function "reg2bins" public. I came across this when re factoring the datomic-to-catalyst repo. It uses the function. I am not sure why I was not getting the error before the change in how the function is called but the error is correct 

ERROR: CompilerException java.lang.IllegalAccessError: reg2bins is not public, compiling:(datomic_rest_api/rest/gene.clj:1:1)

**Comment by mgrbyte** [comment]
:+1: - this was my mistake when I merged the two binning modules (`wb.binning` and `pseudoace.binning`)
