### ISSUE TITLE
#address institution is :boolean instead of :string

### ISSUE THREAD

**Issue by azurebrd** [WormBase/pseudoace#57]
https://github.com/WormBase/pseudoace/blob/master/generated-schemas/schema256.edn#L3450

**Comment by mgrbyte** [comment]
@Paul-Davis I've compared `models.wrm.annot` to `models.wrm`, the former is [missing](https://github.com/WormBase/wormbase-pipeline/blob/master/wspec/models.wrm.annot#L3204) the type annotation `Text` on the Institution tag which is causing this.
Do you know of any reason why this would be dropped?

"Bare" leaf tags such as this will be [converted](https://github.com/WormBase/wormbase-pipeline/blob/master/wspec/models.wrm.annot#L3204) to  boolean.

**Comment by mgrbyte** [comment]
Looks like this was accidentally removed between the following revisions (when the models file used to live in this repository):

```
commit c9fadb95458ea958ddc8afb69be01f53a32bb47c
Author: Matt Russell <matt@mgrbyte.co.uk>
Date:   Tue Apr 5 10:02:43 2016 +0100

    Update text to reflect name change and cleanup.

commit 5426ab4ba70ea435c13dd3075ea1798beeb9d419
Author: Matt Russell <matt@mgrbyte.co.uk>
Date:   Tue Apr 5 10:27:37 2016 +0100

    Unified models file.
```

I'll commit a fix to the `models.wrm.annot` file in wormbase-pipeline.

**Comment by mgrbyte** [comment]
This has been [fixed](https://github.com/WormBase/wormbase-pipeline/commit/9505d70e03c6650922c0c972ce11538bcc6d6cf6) and should be available/visible in WS258.

**Comment by azurebrd** [comment]
Thanks Matt.

**Comment by mgrbyte** [comment]
Converts with change made in 725259c9f7545723994c9642b8375ce32c5e2288
