### ISSUE TITLE
WS257 generated schema

### ISSUE THREAD

**Issue by sibyl229** [WormBase/pseudoace#58]
Hi @mgrbyte when you have time, could you put up the generated schema file for WS257? It's really useful as reference. Thanks!

**Comment by mgrbyte** [comment]
@sibyl229 It'll be on the develop branch tomorrow.

**Comment by sibyl229** [comment]
Thanks a lot @mgrbyte !

**Comment by mgrbyte** [comment]
Note to self - fix #56 first (trivial)

**Comment by mgrbyte** [comment]
Fixed in 7417cdc
