### ISSUE TITLE
Missing data in WS258 onwards

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/pseudoace#71]
The change made to address #54 has resulted in data being missing from some person entities in the migrated datomic database.

The `Institution` tag in the `#Address` model in the annotated models was changed to be `UNIQUE Text` when it should have been just `Text`.  

The importer is [silently swallowing exceptions][1] which meant they were not being noticed (or written to a log file on the migration machine).

The effect being that although the entity exists for e.g `WBPerson2987`, it only contains reference attributes, and none of the scalar ones (e.g first-name, last-name et al) - this being due to the failed transactions caused by there being duplicate `:address/institution` values in the data, but the model attempting to state they are unique.
 
[1]: /WormBase/pseudoace/blob/master/src/pseudoace/ts_import.clj#L885-L888

**Comment by mgrbyte** [comment]
Fixed import process in 0853b93fb2d3d9384efd605db946a0a1121ba1e8

[Fixed][1] annotated models.

[1]: /WormBase/wormbase-pipeline/commit/26746bf03b2352402308c11765a92bc7fdc07756

**Comment by azurebrd** [comment]
Thanks @mgrbyte I can see the Institution data at http://rest-dev.wormbase.org:8888/browse I'll patch the Person overview sometime soon

**Comment by mgrbyte** [comment]
@azurebrd pls wait for WS259 to be migrated and made available before making the changes - the institution data currently in datomic for WS258 is incomplete.

**Comment by azurebrd** [comment]
Ah, got it, I thought that was a longer explanation of what had gotten fixed for the release, as opposed to a new bug being fixed for a future release.  Thanks @mgrbyte
