### ISSUE TITLE
homology DB + testing

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/pseudoace#84]
Because of an incomplete codefix made in azanium 0.7.12, azanium assumes a new name for the homology DB (previously “homol”, now “WS<nr>-homol”), whereas pseudoace 0.7.7 (on which azanium is dependant for creating the homology DB) ignores the provided DB name (provided through the --url argument) and keeps using it’s internal default name “homol”. This caused the backup step to fail (because the homology DB was created with an incorrect name).

Permanent solution is fixing the pseudoace code, which now contains the right name. Will be corrected new Azanium release. Possible to test.

DOD: Fix implemented and tested

**Comment by mluypaert** [comment]
Fixed in commit 8ae68f7a, released as [Pseudoace 0.7.8](https://github.com/WormBase/pseudoace/releases/tag/0.7.8). Will be used in the next azanium release, but currently still to be tested.

**Comment by mluypaert** [comment]
Released as [Azanium 0.7.13](https://github.com/WormBase/db-migration/releases/tag/0.7.13)
